services:
  fhir-db:
    ports:
      - "127.0.0.1:15432:5432"

  vfps:
    ports:
      - "127.0.0.1:8083:8080"

  fhir-server:
    ports:
      - "127.0.0.1:8082:8080"

  fhir-pseudonymizer:
    ports:
      - "127.0.0.1:5000:8080"

  loinc-converter:
    ports:
      - "127.0.0.1:19090:8080"
